aedi: fix setting minimum os version via command line
this resolves the following error after switching from distutils to packaging module
TypeError: '>=' not supported between instances of 'str' and 'Version'